yolo_tracker_node:
  ros__parameters:

    model:
      yolo_weights: "/home/jack/ros2_ws/src/csa_yolo_inference/models/yolov5s.pt"
      conf_threshold: 0.4
      iou_threshold: 0.5

    tracking:
      reid_weights: "/home/jack/ros2_ws/src/csa_yolo_inference/models/osnet_x1_0_market1501.pt"
      device: "0"
      half: true
      max_age: 30
      n_init: 3
      nn_budget: 100

    input:
      mode: "dataset"
      path: "/home/jack/ros2_ws/src/csa_image_input/dataset/rgbd_dataset_freiburg2_desk_with_person_secret/rgb"
      frame_rate: 30
      loop: false
